// Hackathon/reactjs-product-management-boilerplate/src/Components/ProductsData.js
import React from 'react'
import { Button } from 'react-bootstrap';

export default function ProductsData({ products, handleDelete }) {



    return (
        <div>
            <table className="table" >
                <thead>
                    <tr>
                        <th scope="col">#</th>
                        <th scope="col">ProductName</th>
                        <th scope="col">Brand</th>
                        <th scope="col">Quantity</th>
                        <th scope="col">Price</th>
                        <th scope="col">Actions</th>
                    </tr>
                </thead>
                <tbody>
                    {
                        products.map((data) => {

                            return (
                                <tr key={data.id}>
                                    <td>{data.id}</td>
                                    <td>{data.name}</td>
                                    <td>{data.brand}</td>
                                    <td>{data.quantity}</td>
                                    <td>{data.price}</td>
                                    <td><Button variant='danger' onClickCapture={(e) => handleDelete(e, data.id)}>Delete</Button></td>
                                </tr>)

                        })
                    }
                </tbody>
            </table>
        </div>
    )
}

// Hackathon/angular-product-management-boilerplate/src/app/productsdata/productsdata.component.ts
import { Component, EventEmitter, Input, OnInit, Output } from '@angular/core';
import { AppComponent } from '../app.component';
import { Products } from '../products';
import { ProductService } from '../services/product.service';

@Component({
  selector: 'app-productsdata',
  templateUrl: './productsdata.component.html',
  styleUrls: ['./productsdata.component.css']
})
export class ProductsdataComponent implements OnInit {

  @Input() products: Products[] = [];

  constructor(private appService: AppComponent, private productService: ProductService) {
    this.productService.getProducts().subscribe((res) => this.products = res);
  }

  @Output() delete = new EventEmitter<number>();

  deleteProduct(id: number) {
    console.log("left");
    this.delete.emit(id);
    this.ngOnInit()
  }



  ngOnInit() {
  }


}

<div class="container mt-5">
    <table class="table">
        <thead>
            <tr>
                <th scope="col">#</th>
                <th scope="col">ProductName</th>
                <th scope="col">Brand</th>
                <th scope="col">Quantity</th>
                <th scope="col">Price</th>
                <th scope="col">Actions</th>
            </tr>
        </thead>
        <tbody *ngFor="let product of products">
            <tr>
                <th>{{product.id}}</th>
                <th>{{product.name}}</th>
                <th>{{product.brand}}</th>
                <th>{{product.quantity}}</th>
                <th>{{product.price}}</th>
                <th>
                    <Button class="btn btn-danger" (click)="deleteProduct(product.id)">Delete</Button>
                </th>
            </tr>
        </tbody>
    </table>
</div>
